### ISSUE TITLE
How to reproduce your secrets management?

### ISSUE THREAD

**Issue by x10an14** [jakubgs/nixos-config#2]
Hi! First of all, I want to thank you so much for open-sourcing [your implementation of declarative secrets management in nix with pass as a secrets source/store](https://github.com/jakubgs/nixos-config/blob/f5e4efa2b590491d01754e7d73bbc2610ed7256b/roles/secrets.nix)!
I too came across the same article/blog post you reference in one of your comments, and when searching for `builtins.extraBuiltins` in Github I came across this repo.

Below is a paste (unfortunately without syntax highlighting) showing my attempt to incorporate your solution.
The paste also shows the annoying error I get, so I'm left to believe I'm missing something.

Have you got any idea? Maybe you came across this error yourself during the development of this feature?
https://paste.sr.ht/~x10an14/803de4872328be16fa6f19e6f9baf6a3ffdfee16

**Comment by jakubgs** [comment]
It's probably a chicken and egg problem.

1. In order to use `builtins.extraBuiltins` you need to set `extra-builtins-file` in `nix.extraOptions`.
2. In order to set `nix.extraOptions` you need to build the system derivation successfully.
3. In order to build the system derivation successfully you need to have `builtins.extraBuiltins`.

This cannot work. You have to FIRST build a system with an effective `nix.extraOptions` setting for `extra-builtins-file`.

**Comment by x10an14** [comment]
Hi! And thanks for prompt reply!
> It's probably a chicken and egg problem.
> (...) 
> This cannot work. You have to FIRST build a system with an effective `nix.extraOptions` setting for `extra-builtins-file`.

I believe you, it makes sense wrt. my struggles.
Still confuses me though, since I can "bootstrap" my nix's config with other settings like `experimental-commands` (or so I thought).

Would you mind sharing the steps you took to tackle the chicken and egg aspect of this problem?

**Comment by jakubgs** [comment]
I just explained what you need to do in the comment above. Think about it, read it again.

**Comment by x10an14** [comment]
Thanks for your input and time. I ended up getting some help from the nix-plugins' author.

My issue was not the bootstrapping.
I had (1) somehow managed to mismatch the nix-plugin and the nix binary, and (2) I was using the home-manager nix config&binary,  not the nixos one.

**Comment by jakubgs** [comment]
Good you got it resolved. But yeah, this is one of the reasons why I don't use home-manager. It's just too much complexity simply to manage some dotfiles.
